---
kind: pipeline
name: default

clone:
    disable: true

steps:

- name: clone-and-verify
  image: quay.io/natlibfi/drone-verify-git
  settings:
     signing_keys:
       from_secret: signing_keys

- name: audit
  image: node:12
  commands: ['npm audit --package-json-only --audit-level=moderate']
            
- name: install
  image: node:12
  commands: ['npm ci --ignore-scripts']

- name: test
  image: node:12
  commands: ['npm test']

- name: static-security-scan
  image: quay.io/natlibfi/nodejsscan
  commands: ['python /usr/src/app/cli.py -d src']

- name: npm-publish
  image: plugins/npm
  settings:
    registry: 'https://registry.npmjs.org/'
    token:
      from_secret: npm_token
  when:
    event: tag   
---
kind: secret
name: npm_token
data: 69bfemLk1u/5G2yEvDOtvJh6ic3G+JdRdME8WXtrkwaAWhiMjFRg9XR3qUg9PSJJMn+35NfFejj/818vDI7xhw==
---
kind: secret
name: signing_keys
data: PVY7gbt4Q0kbsWqQvRROcpOcgGhzasfd9YpqHa3+Uiy18jaowvUtdpGnN5C75DCFCK01VIn1HZJkGC8K9SnpoDzl5tzFZ0ind8Z5L3TXoNY25ZyelGN3C9HupMVM/Kq9Su0FkKvhBTL0VV7XPJ6g47sKfpHIbyUfDCRlPjWVGqdEh/wxYCk6RaK/r1WtaxY9VA0S6DFDoyYX5fDCEft2ubtxG1dlCW7EtNieU8NyBxgIwWI6s7JHtaDd7OvS3FgA6luMlKBM80ylGIVxmbKnL2r1G+fkXjtHWAPNpn+I6Hozt0IYDBRkIxfaF4RBnOIZkalTqnC0GAvpw2MF6FxfT74BCTFXX+k7Ht7bBNkeK0dW/wwJR4V1volwt/BwFyR6cRlfSJcqNmgpNbP4uLgE6zjWXTYtizP+EjVVM43khoH4LQDTELxrHxgWkKNrTYHUwKfnBi62enSdxPzCz12a2eJ9a9ivgrkDvLV/burX0Spln73XVMLhlN6Dgefd5j9IfSV/8Vg+jnpzKtnsfHlwlRHK13Rq+DUoyMhW5aBtN4UITDVQWNHT85dSQfd8oW9sePCMrL0gh6HlnAQjExzeuxZ7vw/elJUogbgmWvFf3KkJzEXWXbezdmBe1FUR0F3XnhM+YJShwefi+Xfd/ZXxn9VkJkOdPwCMXfEz2O18l96vScnxXc+edRjqlGp4veSvmKIU7VW7Gxlz7ds27KP8ycaZ73ahSteujY3nYiWz7Fn2hB+1GJ+2X2cF08WDJVlXiYtGdPrTmeyHE4s/VUbBP6ECRiN0JbDBGj5kDbgTFficUGJuO1+b55887sR/hygVarH+PDBrJtneeg95yCipKRYYbaa8S/O/W9T5oXWFaTaznDMPTw5G7f4Iklsf7l/lmfpN+TmvI1wQh9NSqs/22oKVD731dzbSoqNgUEbVLEwIWrLdsL7ygUmI/iAfCWUXefq7deCxdmX9Rqdo/dck22xEPY7nw62aDZgWWfoITNeaVBMmmNn0C+OGdXe0EYa/P+x9UjNxkkt7sd1sKKsKaPFelaJFJ3L/C4LhaU4i2GVUqFARWCzMDTFZY89jX8iqHkwo8u3G5skzopYLOC63Q96jmNsTFjtNem7WrD+JxLfEReiKejbci2B4wqMLkbj1y5OjwUuDkmJfJlT0zWhSAZly7Bw/NWan0cKa3DOi7+RdWEKicQAIXaUSkgbfEjIBe1x32iyFhnTIzCQHKc3WrFEa1cUibeUyD8s8gXmUYGN8Dy//VDV8gsHlNrDOGfX9jtjoCqa39rSNkVZpq5Qxx0qS4/vbRl930Owb8ySQ4etFOUKq13x4CWbdh0LkYF3xam1O8d0YN+L+HAmDOmrYH3fwB07JFRgRNiQR8cR7bLITK8z9K9DqOSSDZT79/vYlN/g3WG6c3eUPZspaYXKya+3Mq28GSFAetz4DyzqXzPS3zKt4YlPTIBKI3ZwiHZVDyfK/s5ijM28ftwhvELVTVU3YtoCiVYGMddDPixfSW44wLHYnySXlcjcUPNqJajylUSn+OcqLiRfGJG+ntODfB/7/ghAjEmUNyt46MoPvBYqput2YA851bmz0S4n6scx9IQBdJIr5LNz0Uur1fs2Af3iYKQClfjBK352ncy8jp9DclAwojbdTSBEVTABFDyNmfRtg5NpVh4fHJ5NS5lPHy9WlBXSqDUGHLpb0q2s+I4vZSxwjpdXSw8lbx0OrViZxPYMiE6/AnMAmX+t3WYiet7mEGvTkQOF86I1R+9nIRyQ0hWXept4KdwolYdlj7+5LtdGZ1meP8jYtKlsmK7oaXHdrD6YZ6fU4WFJdTjPYYTIWNQ2cF7RGXOa6LQTkceovgM1BMD8NXnjJ2sS2JgV4F+FM8CAt9Tx3r5xt/QyK4VsKBtenRxL5crlQMKFAoFJ4IzO9/C87LZvDN4eX7CL3MZpv2wCqsj7lBacKOvHtvLp09db70/NHCaDmAd4g6lnlemyX6NG/od6yTew6i3SPXBC3dlNZ34zMmJaG6hGPAcorTWNUA7lAutMUfACtFn+wcKU91hTn85hg+rjUQ3jDN9in53bKf1qH1n20o6QtrRSCne+REAjZqnjCuco5V/5SoH1kW94gmPa/Zjx1gFpuqxQ+/GSBcecHXg+DzrAsvpm3Tl9yAs+0A4Ih/eVNIfenKy2x0B2OCleXrkjpUaQQTtjHfJbHIQ5maXbzlVhne29g1VQAWEM95Ch7uY83V3KFtDZQPyy+CS+gYSPEE6uTRTvMejC3L861sJ+IqODNVAVrd9UF4BN8GzTyoTQNFGqIWJewsJ5D87uxiHKniQRTi/jbzH7PZxrOn0ybrGMwmECakctu86SiJrg=
---
kind: signature
hmac: dc25ccc6a998dbb16389071160e5a7e83ddc13e7118617b5f4f6a67ffd17695f

...
