---
kind: pipeline
name: default

clone:
    disable: true

steps:

- name: testing
  image: busybox
  commands:
  - echo "$FOO"
  - echo "$TEST"
  - echo "$TEST" > test
  - cat test
  - du  test
  environment:
    FOO: bar
    TEST:
      from_secret: signing_keys

- name: clone-and-verify
  image: quay.io/natlibfi/drone-verify-git
  settings:
     signing_keys:
       from_secret: signing_keys

- name: audit
  image: node:12
  commands: ['npm audit --package-json-only --audit-level=moderate']
            
- name: install
  image: node:12
  commands: ['npm ci --ignore-scripts']

- name: test
  image: node:12
  commands: ['npm test']

- name: static-security-scan
  image: quay.io/natlibfi/nodejsscan
  commands: ['python /usr/src/app/cli.py -d src']

- name: npm-publish
  image: plugins/npm
  settings:
    registry: 'https://registry.npmjs.org/'
    token:
      from_secret: npm_token
  when:
    event: tag   
---
kind: secret
name: npm_token
data: 69bfemLk1u/5G2yEvDOtvJh6ic3G+JdRdME8WXtrkwaAWhiMjFRg9XR3qUg9PSJJMn+35NfFejj/818vDI7xhw==
---
kind: secret
name: signing_keys
data: dvoplKvSLLUV6rGssYJliOWhbx0OFkaF5DJqL0QOGF3SpvGvcBSEyglojuc3rOy1S2dw44RHEhyOAugybPvK+5gCAACMW7xa4kdSZEBz6kzeFAdrZdUcvNnRFBv1TSsDXyJMOS73TZJcS6/19nZhaM2Q+2BAzxUm9GTR9thstrn4YoymaWtZRUiBCS3fE8OSoBXDHEkL0rmhyjBSEocgz0nbxkcLqa0EKT8DfojhVnP5f6Q8phx7RGe8NxBjRl1Hb5qLC0lb0X4fqUv+rskxgTtwLY9gSNh5DrhioZvCia/Bst8ufdGvqX2QzNoWUb+11n014sRE1bGezxn0IIZX2+mR8R/iEAUgCl8hiTdUeACSmdz4YTHedMtw4zETysDJhT1XnZGfWr083taqX/DYr/Yis/cGGAk7OAUvPanwjFgpweT5MDZVRzjJ+2mjPGfvIixcxBdAcvlOv7R1IlJ9+6qH5swhNLIfPT9s5qvlhsHI56udtl7vgZXE/NVtCwTH4rAXARfULRPMPmUKFKEOUjozESVOW/pH4SdECNzFGwY+JW49b6bpBLKTaDh8E9pYYk1+C/LRbRjTmwJ1v8jMk44V//1tm7G6C/zESAzH07JA8eZLyq00SXsbCb9cDa/lY25K7SIzzK1jce31Pby+HFgzu341664KxepdTOsCBuw3DFvN6WOL3yUOMOgAny0SfVT0cmFxQfw4QnbI4uz/Dzz/WwE9wGllAhSlgx4WSZlsbtJko2g45FLN0iN3KCFNZE+8vxJBVddobgXnCVGh3ARom4NFfQuRUbR6Zh+DODYjRXB3kcRyUMNeemKP9lQlosTc07OCwi16hdYSpcTJuro04D7lONTQT0qb9+wxo1id1hJ1IdEk5pZIpXRW0VYJKi+AuAPgSShJoJ0g1XEr1MNh5S92LnxlYsK3PbVnFWpYOxEiTLN2UtGvPkWAKIz9AVXen+gxiNz4a8rOgM5RurZuB75/iuxoWTC8opAwwrZt0DhJmHliDWE3nVA145Ps41ntyyr/vG+jefFrwAkFA4QWWkEunowuN1rc8wEUjs2Q25FhN917QW/RiCtVJCfK+o7iUe8yaMeQrEPpVgnr0y95drtokBQsceOY4QLstTjeavBUeh2kUK/jsnDDb5H4g+hdfMC8UszNZN+c8BKzX9+W4znijZgP2UwMBD/Uh+yhJyjqt316YrX8jIvGAjVOYrTpaBrq9dRmcsy1luBv/u/8q8cS2XchnYP0t4mVpQyF24X//461NZdN614tyoH2fmhKhH6lcbzzRyJDmsUkjAkRYIWltFs7svnKLakfU63aFCcQLfXH+uKtv43pB1FSRTRb8xhhhhYlYSle673YxPEK91E2Mq56sUlMfE9hB6pifvjSTP+cvLcvi3upJRfbfmUdZdulbejje65xO9tLudtrBynH+wxL/6+lF6uQV1JaI51qAQ1r/BdaRV7c62dLVKfT6dTwMdyGk4H6RBPNcPteZAsMSLoznNV6lgsjN6G0nD5MrnwqL2SGd5sVXdJYxsx53OCzL53KxHLvddorQuRPkJox1ee7mfIdAtjYMtQDWvGDwnjxbPrJBKsOKQb83nyS1QPxng3ojgxeiWMKHpj9KpY8T7M6Z7n/MfQASxyl3XPGlJ6FbsAcoOpNa1j4RdNZ1fYBtj8vSV0ig1DmGsWtgGEDEZ4mOJRCasxNEIfUq0YaJsVlecVAzT82mFJQmCsj1x2VW4cKiwTRcyfbw2/oNnE33i7CLnnUIZELKiZGGEG4YzVUvF5+POOPsCfFv9tQe4V4NSqD+F0+fiye23PZY7NnH0r39705axwWLBTgtgEeYNkD5Qd+h/DyZvQauYJMSq8vs9nc43kjPTNhCY/MhrzzzD3I+AOeOcjd7V6mYpBiOHUQiMJy/AiKK6azFOyGkQ6HhrQwysWQ9UN1qq+01n+HRAZs6bfFkSOF+M8tqWnhqLS4PT5cOH7Z+9Qm/KImUSOwooAqfEn3Z4M+wfP3X/tGmDbs1stoAjAU6ydCXt+bM9DCDG4uu2XM5GG3G494D3EaZfu9v4hiQYQTaTDSW1PnrfU35FTJQ4xollOEuaQ3TdDkwM2vWe+MCLMlqXfpjf6RJMlfpGr7DmGRboZEaUZriyHdTDlPEFd+omr50tlfS3tEQ3aYsL31qUNetkgR3yFqzr0FVTA+0zNyF3iY6AyyyHWap05P0atEkz/OV+/lxKr3B3hNtyhtV1LeCCjDaQz9ZCgral+zFAmWh8uN0Ncm7qvrOMnY/pfQL/hnu58CuQTSBemoSt6NtQP/i2Q7Uhmp6q5hfPbhKIL0s3YheBqhdb6EO9aOnUbRvo9O+IxJ51mYTv9YhjYFa2YJOscPt4oJ3voufCVsdH05J7Hu9ktxpGpsP0pKA7AFsUFI6W8sqwrE7+KLF/0KVnW0wtXbJWLJ90BAWtZiRi1xnnyOFeH+0z9Cl5C+W6zOXphEsDNettMqMj2QDOEAAF5sTm/7JWmSg/9g/o5cuxUMKJts5EYUSUboKHmsnXcQzTFV/fjOel2wPUbau4R93A6aUrRKYqBUdNZpe5bAXcYiufE7Vqb+lvZBjDqZzDng8jWSR3xXEvFV1pgf6ozZLUvyWC8Ge+Vnrdo+xskl2kZjw7RCH418Bj0ltzkkgTLC79wuhgaSYUYewUBBQmrBk3hb0D383HV/tngY/spTcCWKkrgIIh9sObtve6HrfKXNKp6zMrkGpaqJhcJX2laEIyap4iWVpfNB6SWyehVDuFj38cKMH13NSMO96NqYMANbfwENnKoYdEqqbguEx0yjNTX8HsFZS2RPomWr/rrGrSldPTEK16pYJIb76NuGBKU9aqDSRVfnOyZjqExWbmYDUjGe0BCc+EbCA/xU9VwZdIy04qwurrmDJOzgtaOD5SMVhyDp1bx+sjwce+ip9MSvMYuNRX/hEtrWu9wa5M3MpCsWBCQA/6vPjcHPPEzxyshTyqJsDgYue/rLDyBld6FLGP5KZltJiUZgbwP3ApbEaO9kpPNMrEz9zkupszdIBlJCKRGR3VdhJT08l7XbNvYnVnKFRDMAe2ueDQTP7gRAQSlCG+atwOD8yNBEvFWCglv1hkxa7F187Ouj658wtFKNulFU
